config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'
  # we want it to go TO the pages controller and the about view
  get 'about', to: 'pages#about', as: 'about'

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minumun: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title = 'About Us'
    @content = 'This is the about page!'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id]) # this will get that single post
  end

  def new
    @post = Post.new
  end

  def create
    # render plain: params[:post].inspect # can see what this looks like after we submit the form, its a hash {with the values for title and body}
    @post = Post.new(post_params) # params[:post] means parameters of the post BUT we pass the private function instead.
    if @post.save
      redirect_to @post # this redirects to show view, doesnt exist yet but we can create now
    else
      render 'new'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css
' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container mt-5 pt-3'> 
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">Simpleblog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li><%= link_to "Home", home_path %></li>
        </ul>
        <ul class="navbar-nav mr-auto">
          <li><%= link_to "Create Post", new_post_path %></li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
      </nav>
    </div> 

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/index.html.erb
<h1>Index- should show all posts</h1>
<% @posts.each do |post| %>
  <div class="card">
    <div class="card-body">
      <h3 class="card-title"><%= post.title %></h3>
      <p><%= post.body %></p>
      <%= link_to "Read More", post_path(post), :class => 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>Add Post</h1>

<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class='alert alert-danger'><%= msg %></div>
    <% end %>
<% end %>
<p>
<%= f.label :title %><br>
<%= f.text_field(:title, {:class => 'form control'}) %>
</p>

<p>
<%= f.label :body%><br>
<%= f.text_area(:body, {:class => 'form control'})%>
</p>

<p>
<%= f.submit({:class => 'btn btn-primary'}) %>
</p>
<% end %>

app/views/posts/show.html.erb
<div>
  <h2><%= @post.title %></h2>
  <p><%= @post.body %></p>
<div